# Generated by Django 3.0.7 on 2021-02-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_a_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='B',
        ),
    ]
